[theme]
primaryColor="#a34caf"
backgroundColor="#efe7e7"
secondaryBackgroundColor="#7294da"
textColor="#000000"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[layout]
wideMode = false


